// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seserespvfelkasbxqag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc2VyZXNwdmZlbGthc2J4cWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MDA5MjgsImV4cCI6MjA4ODQ3NjkyOH0.qNmcAjfwtDkP8zvSidUEApD6dfpm00R3vzkx6Kz6iqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});